/* 라인업 문구 레지스트리 — index.html과 terms.html이 함께 쓴다 */
window.LEX_SEED = {
  'rel.on':      { ko:'온쇼어',   def:'바다에서 해변으로 부는 바람. 파도 면이 무너져 거칠어짐', src:'일반 용어' },
  'rel.off':     { ko:'오프쇼어', def:'해변에서 바다로 부는 바람. 파도 면이 매끈해지고 립이 섬', src:'일반 용어' },
  'rel.cross':   { ko:'사이드쇼어', def:'해변과 나란히 부는 옆바람. 파도 면에 결이 생김', src:'일반 용어' },
  'fit.2':       { ko:'정면 ◎', def:'해변이 향한 방향으로 파도가 그대로 들어옴 (에너지 100%)', src:'단톡 코칭 09.22 · 교장쌤' },
  'fit.1':       { ko:'양호 ○', def:'약간 비껴 들어옴 (에너지 대부분)', src:'앱 제안' },
  'fit.0':       { ko:'부분 △', def:'옆에서 들어와 절반쯤 닿음', src:'앱 제안' },
  'fit.-2':      { ko:'차단 ✕', def:'해변이 등진 방향 — 지형·방파제가 막음', src:'단톡 코칭 09.22 · 교장쌤' },
  'verdict.good':{ ko:'좋음',   def:'파고·피리어드·바람이 고루 맞는 날', src:'앱 제안' },
  'verdict.ok':  { ko:'보통',   def:'탈 만하지만 조건이 완벽하진 않음', src:'앱 제안' },
  'verdict.meh': { ko:'약함',   def:'파워가 약하거나 바람이 방해', src:'앱 제안' },
  'verdict.bad': { ko:'나쁨',   def:'입수해도 라이딩이 어려움', src:'앱 제안' },
  'verdict.warn':{ ko:'위험',   def:'파고·바람·뇌우로 입수 금지', src:'앱 제안' },
  'swell.short': { ko:'단주기 윈드 스웰', def:'가까운 바람이 만든 7초 미만 파도. 촘촘하고 힘이 약함', src:'강의노트' },
  'swell.wind':  { ko:'윈드 스웰',       def:'바람으로 만들어진 보통 파도', src:'강의노트' },
  'swell.ground':{ ko:'그라운드 스웰',   def:'먼바다에서 온 정돈된 파도', src:'강의노트' },
  'swell.long':  { ko:'장주기 그라운드 스웰', def:'10~13초. 세트 파워가 강함', src:'강의노트' },
  'swell.xlong': { ko:'초장주기 스웰',   def:'13초 초과. 국내에 드물고 백워시 주의', src:'단톡 코칭 09.09 · 교장쌤' },
  'tide.rise':   { ko:'들물', def:'물이 차오르는 중 (만조로 향함)', src:'일반 용어' },
  'tide.fall':   { ko:'날물', def:'물이 빠지는 중 (간조로 향함)', src:'일반 용어' },
  'tide.slack':  { ko:'정조', def:'물 높이가 거의 멈춘 때', src:'일반 용어' },
  'stage.push':  { ko:'푸쉬업', def:'상체를 세워 중심을 잡는 단계', src:'단톡 코칭 09.08 · 교장쌤' },
  'stage.stand': { ko:'스탠드업', def:'일어서는 동작', src:'단톡 코칭 09.21 · Rio' },
  'stage.ride':  { ko:'라이딩', def:'파도 면을 타고 나아가는 것', src:'일반 용어' },
  'sess.try':    { ko:'도전', def:'파도를 잡으러 패들링해 들어간 횟수', src:'앱 제안' },
  'sess.take':   { ko:'테이크오프', def:'일어서서 파도를 탄 횟수', src:'강의노트' },
  'period':      { ko:'피리어드', def:'파도와 파도 사이 간격(초). 크기보다 중요한 지표, 동해 최적 7~9초', src:'단톡 코칭 09.09 · 교장쌤' },
  'exposure':    { ko:'파도 방향 / 받는 정도', def:'해변이 향한 쪽에서 파도가 들어와야 힘이 온전히 닿음', src:'단톡 코칭 09.22 · 교장쌤' },
};
window.LEX_GROUPS = [
  ['바람', ['rel.on','rel.off','rel.cross']],
  ['파도 방향', ['exposure','fit.2','fit.1','fit.0','fit.-2']],
  ['판정', ['verdict.good','verdict.ok','verdict.meh','verdict.bad','verdict.warn']],
  ['스웰·피리어드', ['period','swell.short','swell.wind','swell.ground','swell.long','swell.xlong']],
  ['물때', ['tide.rise','tide.fall','tide.slack']],
  ['동작·기록', ['stage.push','stage.stand','stage.ride','sess.try','sess.take']],
];
